import { useAuth } from "@/hooks/use-auth";
import { trpc } from "@/lib/trpc";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Redirect, router } from "expo-router";
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";

export default function RequestsScreen() {
  const { user, loading } = useAuth();
  const utils = trpc.useUtils();
  const incoming = trpc.friends.incoming.useQuery(undefined, { enabled: Boolean(user) });
  const respond = trpc.friends.respond.useMutation({ onSuccess: () => { void utils.friends.incoming.invalidate(); void utils.conversations.list.invalidate(); } });
  if (loading) return <ScreenContainer className="items-center justify-center"><ActivityIndicator color="#2563EB" /></ScreenContainer>;
  if (!user) return <Redirect href={"/login" as never} />;
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back" size={22} color="#172554" /></Pressable><View><Text style={styles.title}>Lời mời kết bạn</Text><Text style={styles.subtitle}>Chỉ bạn bè đã kết nối mới có thể nhắn tin.</Text></View></View><FlatList data={incoming.data ?? []} keyExtractor={(item) => String(item.id)} contentContainerStyle={(incoming.data?.length ?? 0) ? styles.list : styles.emptyList} renderItem={({item}) => <View style={styles.row}><View style={styles.avatar}><Text style={styles.avatarText}>{item.user.displayName.slice(0,1).toUpperCase()}</Text></View><View style={styles.info}><Text style={styles.name}>{item.user.displayName}</Text><Text style={styles.username}>@{item.user.username}</Text></View><View style={styles.actions}><Pressable disabled={respond.isPending} onPress={() => void respond.mutateAsync({requestId:item.id,accept:true})} style={styles.accept}><Text style={styles.acceptText}>Chấp nhận</Text></Pressable><Pressable disabled={respond.isPending} onPress={() => void respond.mutateAsync({requestId:item.id,accept:false})} style={styles.decline}><Text style={styles.declineText}>Từ chối</Text></Pressable></View></View>} ListEmptyComponent={<View style={styles.empty}><MaterialIcons name="mark-email-read" size={36} color="#94A3B8"/><Text style={styles.emptyTitle}>Bạn đã xem hết lời mời</Text><Text style={styles.emptyText}>Lời mời mới sẽ xuất hiện tại đây.</Text></View>}/></ScreenContainer>;
}
const styles=StyleSheet.create({header:{paddingHorizontal:20,paddingTop:10,paddingBottom:18,flexDirection:"row",gap:12,alignItems:"center"},back:{width:42,height:42,borderRadius:14,alignItems:"center",justifyContent:"center",backgroundColor:"#E9EFFD"},title:{color:"#172554",fontSize:21,fontWeight:"800"},subtitle:{color:"#718096",fontSize:12.5,marginTop:3},list:{padding:20,gap:10},emptyList:{flexGrow:1,padding:20},row:{backgroundColor:"#FFF",borderRadius:18,borderWidth:1,borderColor:"#E6EAF1",padding:13,alignItems:"center",gap:11},avatar:{width:47,height:47,borderRadius:16,backgroundColor:"#DDE7FB",alignItems:"center",justifyContent:"center"},avatarText:{color:"#1D4ED8",fontSize:18,fontWeight:"800"},info:{alignSelf:"stretch",justifyContent:"center"},name:{color:"#172554",fontWeight:"800",fontSize:16},username:{color:"#718096",fontSize:13,marginTop:2},actions:{flexDirection:"row",gap:8,alignSelf:"stretch",paddingTop:10},accept:{flex:1,minHeight:40,borderRadius:11,backgroundColor:"#2563EB",alignItems:"center",justifyContent:"center"},acceptText:{color:"#FFF",fontWeight:"800",fontSize:13},decline:{minHeight:40,paddingHorizontal:15,borderRadius:11,backgroundColor:"#EEF2F7",alignItems:"center",justifyContent:"center"},declineText:{color:"#5C697D",fontWeight:"800",fontSize:13},empty:{flex:1,alignItems:"center",justifyContent:"center",paddingBottom:90},emptyTitle:{marginTop:15,color:"#475569",fontSize:16,fontWeight:"800"},emptyText:{marginTop:6,color:"#8190A5",fontSize:13}});
