import { useAuth } from "@/hooks/use-auth";
import { trpc } from "@/lib/trpc";
import { clearStoredPushToken, getStoredPushToken } from "@/lib/push-notifications";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Redirect, router } from "expo-router";
import { ActivityIndicator, Alert, Pressable, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";

export default function ProfileScreen() {
  const { user, loading, logout } = useAuth();
  const serverLogout = trpc.auth.logout.useMutation();
  const unregisterDevice = trpc.notifications.unregisterDevice.useMutation();
  if (loading) return <ScreenContainer className="items-center justify-center"><ActivityIndicator color="#2563EB" /></ScreenContainer>;
  if (!user) return <Redirect href={"/login" as never} />;
  const signOut = () => Alert.alert("Đăng xuất", "Bạn sẽ cần đăng nhập lại trên thiết bị này.", [{text:"Hủy",style:"cancel"},{text:"Đăng xuất",style:"destructive",onPress:async()=>{try{const token=await getStoredPushToken();if(token)await unregisterDevice.mutateAsync({token});await clearStoredPushToken();await serverLogout.mutateAsync();}finally{await logout();router.replace("/login" as never);}}}]);
  return <ScreenContainer edges={["top","bottom","left","right"]}><View style={styles.wrap}><Text style={styles.kicker}>TÀI KHOẢN</Text><Text style={styles.title}>Bạn & riêng tư</Text><View style={styles.profileCard}><View style={styles.avatar}><Text style={styles.avatarText}>{user.displayName.slice(0,1).toUpperCase()}</Text></View><View><Text style={styles.name}>{user.displayName}</Text><Text style={styles.username}>@{user.username}</Text></View></View><View style={styles.security}><View style={styles.lock}><MaterialIcons name="lock" color="#16713B" size={19}/></View><View style={{flex:1}}><Text style={styles.securityTitle}>Dữ liệu trò chuyện được bảo vệ</Text><Text style={styles.securityText}>Phiên đăng nhập lưu trong kho bảo mật của thiết bị. Máy chủ chỉ cấp quyền cho thành viên hội thoại.</Text></View></View><Pressable onPress={() => router.push("/settings" as never)} style={({pressed})=>[styles.settings,pressed&&styles.pressed]}><MaterialIcons name="security" size={20} color="#1D4ED8"/><View style={{flex:1}}><Text style={styles.infoTitle}>Khóa ứng dụng & thông báo</Text><Text style={styles.infoText}>Đặt mã khóa, ẩn thông báo và xem giới hạn video.</Text></View><MaterialIcons name="chevron-right" size={22} color="#94A3B8"/></Pressable><View style={styles.info}><MaterialIcons name="person-search" size={20} color="#2563EB"/><View style={{flex:1}}><Text style={styles.infoTitle}>Tìm bạn bằng tên người dùng</Text><Text style={styles.infoText}>Bạn bè đã chấp nhận mới có thể nhắn tin với bạn.</Text></View></View><Pressable onPress={signOut} style={({pressed})=>[styles.logout,pressed&&styles.pressed]}><MaterialIcons name="logout" size={20} color="#C92A2A"/><Text style={styles.logoutText}>Đăng xuất khỏi thiết bị</Text></Pressable></View></ScreenContainer>;
}
const styles=StyleSheet.create({wrap:{flex:1,padding:22},kicker:{color:"#2563EB",fontSize:11,fontWeight:"800",letterSpacing:1.4},title:{color:"#172554",fontSize:29,fontWeight:"800",letterSpacing:-.6,marginTop:3},profileCard:{marginTop:24,padding:18,borderRadius:22,backgroundColor:"#FFF",borderWidth:1,borderColor:"#E6EAF1",flexDirection:"row",alignItems:"center",gap:13},avatar:{width:58,height:58,borderRadius:20,backgroundColor:"#DDE7FB",alignItems:"center",justifyContent:"center"},avatarText:{color:"#1D4ED8",fontWeight:"800",fontSize:23},name:{color:"#172554",fontSize:18,fontWeight:"800"},username:{color:"#718096",fontSize:14,marginTop:4},security:{marginTop:18,padding:16,borderRadius:19,backgroundColor:"#ECFDF3",flexDirection:"row",gap:12},lock:{width:36,height:36,borderRadius:12,backgroundColor:"#D5F5E2",alignItems:"center",justifyContent:"center"},securityTitle:{color:"#17613B",fontSize:14,fontWeight:"800"},securityText:{color:"#4E7460",fontSize:12.5,lineHeight:18,marginTop:4},info:{marginTop:13,padding:16,borderRadius:19,backgroundColor:"#FFF",borderWidth:1,borderColor:"#E6EAF1",flexDirection:"row",gap:12},settings:{marginTop:13,padding:16,borderRadius:19,backgroundColor:"#EEF4FF",borderWidth:1,borderColor:"#D8E6FF",flexDirection:"row",alignItems:"center",gap:12},infoTitle:{color:"#334155",fontSize:14,fontWeight:"800"},infoText:{marginTop:4,color:"#718096",fontSize:12.5,lineHeight:18},logout:{marginTop:"auto",minHeight:52,paddingHorizontal:16,borderRadius:15,borderWidth:1,borderColor:"#F3D2D2",backgroundColor:"#FFF5F5",flexDirection:"row",alignItems:"center",justifyContent:"center",gap:9},logoutText:{color:"#C92A2A",fontSize:15,fontWeight:"800"},pressed:{opacity:.7,transform:[{scale:.98}]}});
